<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Emlakcim.BLL\Emlakcim.BLL.csproj" />
    <ProjectReference Include="..\Emlakcim.Entity\Emlakcim.Entity.csproj" />
  </ItemGroup>

</Project>
