<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Emlakcim.DAL\Emlakcim.DAL.csproj" />
    <ProjectReference Include="..\Emlakcim.Entity\Emlakcim.Entity.csproj" />
  </ItemGroup>

</Project>
